export const data = [
    { word: "apple", hint: "fruit" },
    { word: "banana", hint: "yellow fruit" },
    { word: "carrot", hint: "orange vegetable" },
    { word: "elephant", hint: "large mammal" },
    { word: "guitar", hint: "musical instrument" },
    { word: "ocean", hint: "large body of water" },
    { word: "computer", hint: "electronic device" },
    { word: "mountain", hint: "elevated landform" },
    { word: "umbrella", hint: "rain protection" },
    { word: "penguin", hint: "flightless bird" },
    { word: "lion", hint: "wild cat" },
    { word: "blueberry", hint: "small, blue fruit" },
    { word: "kiwi", hint: "brown, fuzzy fruit" },
    { word: "parrot", hint: "colorful bird" },
    { word: "tomato", hint: "red vegetable/fruit" },
    { word: "strawberry", hint: "red berry" },
    { word: "butterfly", hint: "colorful insect" },
    { word: "cucumber", hint: "green vegetable" },
    { word: "chocolate", hint: "sweet treat" },
    { word: "peacock", hint: "colorful bird with feathers" },
    { word: "broccoli", hint: "green vegetable" },
    { word: "cheetah", hint: "fast-running big cat" },
    { word: "potato", hint: "starchy vegetable" },
    { word: "rose", hint: "red flower" },
    { word: "lemon", hint: "yellow citrus fruit" },
  ];
export const Alphabets = [
  "a",
  "b",
  "c",
  "d",
  "e",
  "f",
  "g",
  "h",
  "i",
  "j",
  "k",
  "l",
  "m",
  "n",
  "o",
  "p",
  "q",
  "r",
  "s",
  "t",
  "u",
  "v",
  "w",
  "x",
  "y",
  "z",
];
